# Generated by Django 5.2.12 on 2026-03-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('benchmarks', '0001_initial'),
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('num_questions', models.IntegerField(default=0, help_text='Number of questions to run (0 = all)')),
                ('system_prompt', models.TextField(blank=True)),
                ('temperature', models.FloatField(default=0.0)),
                ('max_tokens', models.IntegerField(default=512)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_questions', models.IntegerField(default=0)),
                ('correct_answers', models.IntegerField(default=0)),
                ('score', models.FloatField(default=0.0, help_text='Score as percentage 0-100')),
                ('error_message', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('thread_id', models.CharField(blank=True, help_text='Thread identifier for cancellation', max_length=100)),
                ('benchmark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='benchmarks.benchmark')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='providers.provider')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RunResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_response', models.TextField()),
                ('parsed_answer', models.CharField(max_length=100)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('response_time', models.FloatField(default=0.0, help_text='Response time in seconds')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='benchmarks.benchmarkquestion')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='runs.benchmarkrun')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
