# Generated by Django 5.2.4 on 2026-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('runs', '0003_suiterun_scheduled_run_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('model_name', models.CharField(max_length=200)),
                ('temperature', models.FloatField(default=0.0)),
                ('max_tokens', models.IntegerField(default=512)),
                ('system_prompt', models.TextField(blank=True)),
                ('num_questions', models.IntegerField(default=0, help_text='0 = use all benchmark questions')),
                ('parallel_workers', models.IntegerField(default=1)),
                ('few_shot_count', models.IntegerField(default=0)),
                ('use_cot', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
