# Generated by Django 5.2.12 on 2026-03-10 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('provider_type', models.CharField(choices=[('ollama', 'Ollama'), ('vllm', 'vLLM'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic'), ('cohere', 'Cohere'), ('mistral', 'Mistral'), ('gemini', 'Google Gemini'), ('groq', 'Groq'), ('together', 'Together AI'), ('custom', 'Custom')], max_length=50)),
                ('base_url', models.CharField(blank=True, help_text='Base URL for local providers', max_length=500)),
                ('api_key', models.CharField(blank=True, help_text='API key (stored plain, use env vars in production)', max_length=500)),
                ('default_model', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('extra_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProviderTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_time', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('tested_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='providers.provider')),
            ],
            options={
                'ordering': ['-tested_at'],
            },
        ),
    ]
